defaults: &defaults
  images:
    sizes:
      small_avatar: "40x40"
  roles:
    admin: "admin"
    recruiter: "recruiter"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
