defaults: &defaults
  images:
    sizes:
      small_avatar: "40x40"
      xsmall_avatar: "30x30"
      media_post: "80"
  roles:
    admin: "admin"
    recruiter: "recruiter"
  notifications:
    limit_show: 20
    notify_types:
      apply_job: "apply_job"
      share_post: "share_post"
  truncates:
    content_post_length: 150

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
